Minor changes towards GPU compatibility
JuliaGaussianProcesses/AbstractGPs.jl pull request #236
Opened 2021-10-28 10:50 UTC by st--

Replaces `Diagonal(Fill(sigma2, n))` with `PDMats.ScalMat(n, sigma2)`, which plays better with CUDA. (And the noise covariance should be positive definite anyways.)

2021-11-02 11:21 UTC, willtebbutt commented on src/finite_gp_projection.jl
> +    return FiniteGP(f, x, ScalMat(length(x), σ²))
> if we don't use vectors in the homoscedastic case anymore (which IMO is a good change).

Technical point: we actually never did. There are a number of outer constructors for `FiniteGP` that would ensure that a matrix is the thing you wind up with inside the FiniteGP is a matrix. Specifically, there's a method which expects a vector for the noise, and puts it inside a `Diagonal` matrix and passes it along.

2021-11-02 15:11 UTC, st-- commented on src/finite_gp_projection.jl
> +    return FiniteGP(f, x, ScalMat(length(x), σ²))
@devmotion please let me know if Will's response doesn't address your point sufficiently, but otherwise I consider it resolved for now

2021-11-02 15:19 UTC, devmotion commented on src/finite_gp_projection.jl
> +    return FiniteGP(f, x, ScalMat(length(x), σ²))
I don't think the comment addresses or resolves my main point that we should restrict the type parameter to `AbstractMatrix`.

2021-11-02 15:21 UTC, willtebbutt commented on src/finite_gp_projection.jl
> +    return FiniteGP(f, x, ScalMat(length(x), σ²))
I'm pro the restriction. It should have been there all along -- I'm happy to view it as a bug-fix.

2021-11-02 16:23 UTC, st-- commented
> Have you checked if the `Diagonal{Fill}` PR in FillArrays solves the original issue?

Do you mean https://github.com/JuliaArrays/FillArrays.jl/pull/165/files ?
No, I've not checked that yet. I left a note on https://github.com/JuliaGPU/GPUArrays.jl/issues/381.

If that turned out to resolve the GPU issue, would you prefer to undo the change here (and hope the PR will get merged & released sooner rather than later), or should we stick with the ScalMat anyways (because it _should_ be positive definite) - and perhaps change the other cases over to PDiagMat and PDMat as well? :thinking: 

> Then we could use a `Diagonal(Fill(...))` instead of `Fill`.

We were already using `Diagonal(Fill(...))` before, so not sure what you intend here?


> I also suggest restricting the type parameter to `AbstractMatrix` to really enforce the use of matrices. Otherwise I am worried that some old code might return wrong values silently if we don't use vectors in the homoscedastic case anymore (which IMO is a good change).

It's always been matrices, see [@willtebbutt's comment](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/236#discussion_r740961392).

> Can you revert unrelated changes such as removing `_symmetric`?

I can't _revert_ them per se, it would then require adding a bunch of extra code instead, as I [pointed out before](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/236#discussion_r738945173) and while we _could_ split it into two separate PRs, I'm not convinced why that would be worth the extra effort if after merging the other PR it would look exactly as if we just merged this one as-is.

2021-11-02 16:36 UTC, willtebbutt commented on src/finite_gp_projection.jl
> +    return FiniteGP(f, x, ScalMat(length(x), σ²))
> I have to say I find it quite confusing when it's good to add a type restriction because that'll prevent errors and when it's bad to add a type restriction because it'll make it less flexible. 😅 I mean, both of those are generally true. But why that results in wanting it sometimes and not wanting it other times.

In my view it's a judgement call each time -- I also don't have a standard set of rules for when I type stuff really strictly vs not.

In this case, my feeling is that knowing that you're going to get an `AbstractMatrix{<:Real}` (as a GP-implementer) is very helpful -- there's a good chance that `logdet`, `Cholesky`, and `\` are going to work (which is not the case for `Real`s, `AbstractVector{<:Real}`s, `UniformScaling`s etc), I can check the `size` if I like, I can specialise on particular matrix types etc if I know something particular about the structure of certain matrices. So it lets me make slightly stronger assumptions about the internals that are more likely to be true, and it doesn't restrict the user-facing interface.

> We can't make the same restriction for LatentGP though, as at that point we don't actually know the length of the observation vector, so the jitter Σy actually needs to be a scalar, or a vector or matrix of the right shape (it simply gets passed to FiniteGP in the construction of LatentFiniteGP)...

Indeed. I think that's fine though, because it's a different type and I'm okay with it having different semantics. We should probably rename it to jitter and restrict it to be a `Real` at some point...

2021-11-03 17:13 UTC, devmotion commented
> It's always been matrices

The main point is that it was possible to use vectors (even though the default constructors did not use them which I missed initially and @willtebbutt noticed) and that it therefore would be reasonable to restrict the type parameter to `AbstractMatrix`

> I'm not convinced why that would be worth the extra effort if after merging the other PR

One advantage would be that this PR could be viewed as non-breaking without the `_symmetric` changes (I would argue replacing `Diagonal{Fill}` with `ScalMat` can be viewed as non-breaking, but surely this could be considered breaking as well). I am pretty sure that removing `_symmetric` breaks code of users that could rely on us taking care of tiny numerical asymmetries. Additionally, while I think the reasoning for removing `_symmetric` is conceptually appealing, I am worried that it will lead to a worse user experience and hence I am not sure if it is actually a good idea and should be done.

2021-11-03 17:39 UTC, devmotion commented
> If that turned out to resolve the GPU issue, would you prefer to undo the change here (and hope the PR will get merged & released sooner rather than later), or should we stick with the ScalMat anyways (because it should be positive definite) - and perhaps change the other cases over to PDiagMat and PDMat as well?

I think we shouldn't use any of these matrix types actually for now since a) they do not support positive semi-definite matrices and b) `PDMat` is implemented very inefficiently. Therefore I think maybe we should also not use `ScalMat` if `Diagonal{Fill}` works.

2021-11-03 19:48 UTC, st-- commented
> I think the reasoning for removing `_symmetric` is conceptually appealing, I am worried that it will lead to a worse user experience and hence I am not sure if it is actually a good idea and should be done.

Whereas I think it will lead to a _better_ user experience... what do we do with that then?

2021-11-03 19:52 UTC, st-- commented
> I think we shouldn't use any of these matrix types actually for now since a) they do not support positive semi-definite matrices (one would have to use e.g. PSDMats) and b) `PDMat` is implemented very inefficiently. Therefore I think maybe we should also not use `ScalMat` if `Diagonal{Fill}` works.

Well, the `Diagonal{Fill}` _doesn't_ work. `ScalMat(N, 0.0)` does actually work though.

2021-11-03 19:53 UTC, st-- commented
> `PDMat` is implemented very inefficiently.

What would it take to write a more efficient version ?

2021-11-03 19:55 UTC, st-- commented
> One advantage would be that this PR could be viewed as non-breaking

I don't think we're at the point yet where we should be too concerned about breaking things... there's way too many things that don't work at all. Once we're at the point where we could honestly recommend this over GaussianProcesses.jl, we should be more careful; for now, I'd rather see us get there faster.

2021-11-03 22:44 UTC, devmotion commented
> Whereas I think it will lead to a _better_ user experience... what do we do with that then?

As I said, I like the suggestion :slightly_smiling_face: I just think there are different consequences (and possibly alternatives) to consider before removing `_symmetric`. To me this discussion and our disagreement just indicates that it would be good to discuss it (and possibly remove it) in a separate PR.

> Well, the `Diagonal{Fill}` _doesn't_ work.

It does work, GP projections constructed with something like `gp(rand(5), 0.0)` (i.e., without noise) work fine currently. So it is a valid question if this would be broken by switching to `ScalMat` since in general PDMats is not concerned with positive semi-definite but only positive definite matrices. I just checked quickly and it seems e.g. `cov`, `var`, `rand`, and `logpdf` still work :+1: Thus probably only `PDMat` would not work with positive semi-definite matrices (I assume `PDDiagMat` would work in the same way as `ScalMat` since it just computes the inverses of the diagonal elements, resulting in `Inf` values if a diagonal entry is 0).

> What would it take to make it more efficient (or write a more efficient version) ?

I assume one would have to define a new `AbstractPDMat` type that does not always compute the full matrix. (xref: https://github.com/JuliaStats/PDMats.jl/issues/140)

> I don't think we're at the point yet where we should be too concerned about breaking things... there's way too many things that don't work at all. Once we're at the point where we could honestly recommend this over GaussianProcesses.jl, we should be more careful; for now, I'd rather see us get there faster.

I am not worried about making a breaking release, we have to do this anyway from time to time since the API and types still change. And I think it's fine. But there's still an advantage of non-breaking releases - downstream packages and users will receive the new version and hence the new features automatically without any delay and without having to update compat bounds. Whereas for breaking releases they have to update the compat bounds, make a new release, etc. - which is fine and usually not a problem but takes time.

IMO AbstractGPs also already works quite well and for many things it should be possible to use it instead of GaussianProcesses.jl. I think also one major advantage of AbstractGPs is that one can choose from the variety and combinations of kernels in KernelFunctions, whereas the design of kernels in GaussianProcesses.jl always seemed a bit suboptimal to me (note: I worked on it and tried to improve it a while back).

2022-03-30 07:18 UTC, st-- commented on src/sparse_approximations.jl
> +    U_y = _cholesky(fx.Σy).U
separated out in #239

2022-03-30 07:42 UTC, st-- commented on src/finite_gp_projection.jl
> +    return FiniteGP(f, x, ScalMat(length(x), σ²))
#305

2022-03-30 09:24 UTC, devmotion requested changes
Maybe it would be useful to convert `Diagonal(Fill(...))` to a `ScalMat` in thw constructor. Then the internal implementation could be simplified since we would only have to handle `ScalMat`.

2022-03-30 09:24 UTC, devmotion commented on Project.toml
> +PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Can you add a compat entry and update the version number?

2022-03-30 09:24 UTC, devmotion commented on src/finite_gp_projection.jl
> +struct FiniteGP{Tf<:AbstractGP,Tx<:AbstractVector,TΣ<:AbstractMatrix{<:Real}} <: AbstractMvNormal
This is a breaking change and hence requires a breaking release.

2022-03-30 09:24 UTC, devmotion commented on src/sparse_approximations.jl
> +    return sum(var(f.f, f.x) / Σy)
This is just

```suggestion
    return sum(var(f.f, f.x)) / Σy.value
```
or, without accessing internal fields that could possibly be changed and then break AbstractGPs,

```suggestion
    return sum(var(f.f, f.x)) / first(Σy)
```

2022-03-30 09:24 UTC, devmotion commented on test/Project.toml
> +PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Compat entry is missing.

2022-03-30 11:14 UTC, st-- commented on src/finite_gp_projection.jl
> +struct FiniteGP{Tf<:AbstractGP,Tx<:AbstractVector,TΣ<:AbstractMatrix{<:Real}} <: AbstractMvNormal
I included it because @willtebbutt saw it as a bugfix (https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/236#discussion_r741187335). I agree with Will on that - it makes no sense to have had anything else in here (I don't see how the code would've been able to run with anything else, anyways). But if you can't get on board with that then I can just take it out again.

2022-03-30 11:22 UTC, st-- commented
> Maybe it would be useful to convert `Diagonal(Fill(...))` to a `ScalMat` in thw constructor. Then the internal implementation could be simplified since we would only have to handle `ScalMat`.

I'm not quite sure what you mean; we still support `Diagonal(vec)` (different noise at each observation), I don't understand neither what exactly you're suggesting nor what/why we're gaining from it...

2022-03-30 11:45 UTC, devmotion commented
Well, the suggestion was not to drop support for Diagonal(Fill(...)) but simply to convert them to ScalMat when a FiniteGP is constructed. The main advantage is that Diagonal(Fill(...)) would hit the same internal optimizations as ScalMat but we only have to implement them for ScalMat. Similar to eg observations as Matrix but internally we only have to deal with vectors.

2022-03-30 11:53 UTC, devmotion requested changes

2022-03-30 11:53 UTC, devmotion commented on Project.toml
> +version = "0.5.10"
The PR is breaking:
```suggestion
version = "0.6.0"
```

2022-03-30 11:57 UTC, willtebbutt commented on src/finite_gp_projection.jl
> +struct FiniteGP{Tf<:AbstractGP,Tx<:AbstractVector,TΣ<:AbstractMatrix{<:Real}} <: AbstractMvNormal
Yes. This is absolutely intended to be the case -- it should never be the case that you wind up with anything that is not a subtype of `AbstractMatrix` as the observation noise covariance matrix in a `FiniteGP`, so definitely a bug fix.

2022-03-30 12:00 UTC, willtebbutt commented
> Well, the suggestion was not to drop support for Diagonal(Fill(...)) but simply to convert them to ScalMat when a FiniteGP is constructed. The main advantage is that Diagonal(Fill(...)) would hit the same internal optimizations as ScalMat but we only have to implement them for ScalMat. Similar to eg observations as Matrix but internally we only have to deal with vectors.

I'm not sure that this is necessary. The standard way to obtain a `Diagonal(Fill(...))` as the covariance matrix is to just pass in a scalar. i.e. to write `f(x, 0.1)`, rather than `f(x, Diagonal(Fill(0.1, length(x))))`.

2022-03-30 12:03 UTC, st-- commented
@devmotion I've removed the type restriction; I still believe it's just enshrining at the constructor level what was already required by the code everywhere else, but someone else can sort that out separately. That should make sure this is no longer breaking.

If you want to add an additional outer constructor for Diagonal{<:Fill}, please do so in a separate PR; as Will pointed out I don't think it's really necessary, and I'd rather just get this PR merged in instead of figuring out how to get the details of that right.

Anything else that's in the way of being able to merge this ?

2022-03-30 12:54 UTC, devmotion commented
A type change is breaking, eg it is not possible anymore to use `UniformScaling` which supported by at least parts of the code it seems (can't check at a computer right now).

Another possibility would be even to only support matrices as noise but no scalars or vectors. This was changed this way eg in MvNormal since it was always unclear to users if scalars and vectors represent variances or standard deviations in MvNormal whereas matrices are always covariance matrices. If we expect users to provide matrices it would be a stronger argument for handling Diagonal(Fill(...)) explicitly.

I'll try to have another look at the PR later today and check if anything is missing.

___

Slightly off-topic, I think it's off-putting if I feel to be pushed into reviewing as fast as possible (even if this was not your intention it is how I read your comment; but as almost everyone, I do this in my limited spare time) and if it is demanded if suggestions within the scope of the PR should be implemented by myself (sometimes this might be useful but even if something is considered to be out of scope - by the people involved in the discussion - I don't think it's the reviewer's job to fix such outstanding issues in follow-up PRs).

2022-03-30 13:01 UTC, willtebbutt commented
> A type change is breaking, eg it is not possible anymore to use UniformScaling which supported by at least parts of the code it seems (can't check at a computer right now).

This is not correct. Code written for the `FiniteGP` type does not support `UniformScaling` scalars / vectors as the observation noise covariance. If such types are passed, outer constructors are used to convert them into appropriate `AbstractMatrix` objects. The lack of a type constraint is an omission, and therefore a bug. For example, if you take a look through [this](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/master/src/finite_gp_projection.jl) code, you'll see that there are a lot of things that are done that are only safe to do with `AbstractMatrix`s. For example [this](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/f96c05bd526a367da18fc9c83014277d2fb36dcd/src/finite_gp_projection.jl#L157).

2022-03-30 13:47 UTC, st-- commented
> Slightly off-topic, I think it's off-putting if I feel to be pushed into reviewing as fast as possible (even if this was not your intention it is how I read your comment; but as almost everyone, I do this in my limited spare time)

I did not mean to push you into reviewing faster, I would also be happy for you to declare that you don't have time to review it, and to let someone else do it instead. It's just that by requesting changes you give the impression that you are keen to review it, with other people then leaving the reviewing to you, so thereby you're blocking the PR from improving the status quo.

The bar for a PR to be merged should not be "it's perfect", just that it improves things. I'm also putting my limited spare time into this, and what is off-putting to me is if I feel like anything I try to improve isn't good enough until it's perfect.

> if it is demanded if suggestions within the scope of the PR should be implemented by myself (sometimes this might be useful but even if something is considered to be out of scope - by the people involved in the discussion - I don't think it's the reviewer's job to fix such outstanding issues in follow-up PRs).

Of course it doesn't _have_ to be you to be the one to implement it. You seemed keen to have it in place, and you gave the impression that you knew just what needed doing. I just wanted to suggest that this is an additional change on top of what's already in this PR (so nothing that "needs to be fixed", which would make it any worse than it is right now), and that I don't think this PR should be held up by adding your proposal. We could of course just open an issue to keep track of it instead!

2022-03-30 15:22 UTC, devmotion commented
> This is not correct. Code written for the `FiniteGP` type does not support `UniformScaling` scalars / vectors as the observation noise covariance. If such types are passed, outer constructors are used to convert them into appropriate `AbstractMatrix` objects. The lack of a type constraint is an omission, and therefore a bug. For example, if you take a look through [this](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/master/src/finite_gp_projection.jl) code, you'll see that there are a lot of things that are done that are only safe to do with `AbstractMatrix`s. For example [this](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/f96c05bd526a367da18fc9c83014277d2fb36dcd/src/finite_gp_projection.jl#L157).

I just checked and `UniformScaling` is supported and can be used at least with some methods (`mean_and_var` errors since `diagind` is not defined):
```julia
julia> using AbstractGPs, LinearAlgebra


julia> fx = GP(GaussianKernel())(rand(10), 2.0*I)
AbstractGPs.FiniteGP{GP{AbstractGPs.ZeroMean{Float64}, SqExponentialKernel{Distances.Euclidean}}, Vector{Float64}, UniformScaling{Float64}}(
f: GP{AbstractGPs.ZeroMean{Float64}, SqExponentialKernel{Distances.Euclidean}}(AbstractGPs.ZeroMean{Float64}(), Squared Exponential Kernel (metric = Distances.Euclidean(0.0)))
x: [0.9001122128843618, 0.5014532689115688, 0.9068485710635356, 0.8671710704251859, 0.1593165289491113, 0.033849226130907684, 0.6012613832007633, 0.6792056597108606, 0.6291170664768985, 0.4586633196418336]
Σy: UniformScaling{Float64}(2.0)
)


julia> mean(fx)
10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

julia> mean_and_cov(fx)
([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [3.0 0.9236108289936744 … 0.9639467883634513 0.9071580732113963; 0.9236108289936744 3.0 … 0.9918840906723075 0.9990849290537535; … ; 0.9639467883634513 0.9918840906723075 … 3.0 0.9855777713218073; 0.9071580732113963 0.9990849290537535 … 0.9855777713218073 3.0])

julia> rand(fx)
10-element Vector{Float64}:
  3.7182207380247623
  1.0497036329028469
  0.9905553822300871
 -0.44238892519088857
 -1.0465937939874175
 -0.8895511203455914
  1.0418168460349009
 -0.20439667340116374
  1.2400217065941217
  0.12529989634261757
```

2022-03-30 15:30 UTC, willtebbutt commented
Okay, that's interesting. Since @st-- has removed it from this PR, I think we should continue this discussion elsewhere, and let this PR get merged.

2022-03-30 20:17 UTC, devmotion approved these changes
LGTM :+1:

2022-03-30 20:29 UTC, devmotion commented
> I did not mean to push you into reviewing faster, I would also be happy for you to declare that you don't have time to review it, and to let someone else do it instead. It's just that by requesting changes you give the impression that you are keen to review it, with other people then leaving the reviewing to you, so thereby you're blocking the PR from improving the status quo.

I'm completely fine with reviewing it as you can see. But IMO reviewing within < 2 days is fast and usually there is no good reason to expect a faster review cycle. It's completely fine to ping me after a few days without review/response (sometimes I just forget stuff), but pinging immediately with a comment about not holding back the PR doesn't feel appropriate to me. I guess different people have different opinions on this matter though :shrug: 

> The bar for a PR to be merged should not be "it's perfect", just that it improves things.

Sure, nothing is ever perfect. But removing breaking changes, fixing missing compat entries, discussing possible constructors to not miss out on newly added optimizations etc. are all reasonable things to suggest and discuss, and not something I do to hold back the PR.

> We could of course just open an issue to keep track of it instead!

Yeah, I think usually this would be the way to go. Then anyone who is keen and has time can fix it.

2022-03-31 09:02 UTC, merged