clean up mean_function tests without reactivating AD
JuliaGaussianProcesses/AbstractGPs.jl pull request #315
Opened 2022-04-07 12:51 UTC by st--

2022-04-07 13:01 UTC, devmotion requested changes

2022-04-07 13:01 UTC, devmotion commented on test/mean_function.jl
```suggestion
```

2022-04-07 13:01 UTC, devmotion commented on test/mean_function.jl
> +
```suggestion
```

2022-04-07 13:56 UTC, st-- commented on test/mean_function.jl
>  @testset "mean_functions" begin
If the exact random numbers matter, then it makes sense to explicitly state which random number generator you use (otherwise your tests might suddenly fail once julia moves to a new default).

If the exact random numbers don't matter, then it shouldn't even need the Random.seed! ... no?

2022-04-07 13:59 UTC, devmotion commented on test/mean_function.jl
>  @testset "mean_functions" begin
No. The random numbers may be (and probably are) different for different Julia versions and hardware architectures anyway. Setting a seed is only useful to avoid spurious test failures with numerically bad samples - they are quite rare here I assume but without any seed we might eventually get them in some test run.

2022-04-07 14:12 UTC, st-- commented on test/mean_function.jl
>  @testset "mean_functions" begin
So, hypothetically, you might still eventually get that issue at some julia version upgrade.
What's the problem with keeping the MersenneTwister then ? Why would it be needed that I add this one additional change?

2022-04-07 14:13 UTC, st-- commented on test/mean_function.jl
> +    xD′ = RowVecs(randn(rng, N, D))
can we just leave it as is? it IS the adjoint under the hood... I think it's already more readable than it was before this PR

2022-04-07 14:18 UTC, devmotion commented on test/mean_function.jl
>  @testset "mean_functions" begin
It's not strictly necessary but a) it seems simpler and b) allows us to test the methods with the default, and hence most likely used, RNGs. b) can also lead to a speed-up in more recent Julia versions.

2022-04-07 14:18 UTC, st-- commented on test/mean_function.jl
>  @testset "mean_functions" begin
I don't think it should be necessary in this PR. please change separately if you care.

2022-04-07 14:34 UTC, devmotion commented on test/mean_function.jl
>  @testset "mean_functions" begin
I really don't understand why you're so hesitant to take up any suggestions and basically always suggest to "just do it later". This is very frustrating, and in my opinion also unproductive. In this PR these lines are changed so it's the perfect opportunity for such improvements, in particular if they are so simple.

2022-04-07 14:49 UTC, st-- commented on test/mean_function.jl
>  @testset "mean_functions" begin
Just clean something up as I go along is something that I thought at other times, too, only to get a comment from you complaining that I changed something else.

I'm hesitant to take up your suggestions because it's *more work*. Sure I could accept your suggestion, then I have to go and fix the other uses of `rng`. Maybe it would make it even better than what I proposed. But I don't have the time to make everything perfect! It gets to the point where it seems that proposing _any_ change ends up taking hours of back and forth, even though it would have already improved a _bit_ over the status-quo already.

The measure for whether a PR should be merged or not shouldn't be "is this the best it could possibly be?", only "does this improve over what we had before?" (implying it doesn't make anything else worse in the process).

2022-04-08 09:11 UTC, devmotion commented
I unsubscribed, please find another reviewer.

2022-04-08 16:21 UTC, yebai approved these changes

2022-04-08 16:23 UTC, yebai commented
Many thanks, @st-- for the nice improvements! I think it's ready to get merged. 

Also many thanks to @devmotion for the thorough and thoughtful reviews all the time.

2022-04-08 16:23 UTC, merged